name: Jest Unit Test and Coverage on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests and generate coverage
        run: npm test -- --coverage

      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage

  check-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download coverage from previous job
        uses: actions/download-artifact@v2
        with:
          name: coverage

      - name: Check test coverage
        run: |
          threshold=$(jq -r ".coverageThreshold.global.lines" coverage/lcov-report/coverage-summary.json)
          if [ $(echo "$threshold < 90" | bc) -eq 1 ]; then
            echo "Error: Test coverage is below the threshold."
            exit 1
          fi
