name: Jest Unit Test and Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests and generate coverage
        run: yarn test -- --coverage

      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
