name: Jest Unit Test and Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Identify Modified Files
        id: modified-files
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > modified-files.txt
          echo "::set-output name=modified_files::$(cat modified-files.txt)"

      - name: Run Jest for Modified Files
        run: |
          modified_files="${{ steps.modified-files.outputs.modified_files }}"
          if [ -n "$modified_files" ]; then
            yarn test:ci --findRelatedTests $modified_files | tee ./coverage.txt && exit $?
          else
            echo "No modified files to test."
          fi
